jupyter/jupyter-packaging

jupyter_distutils.py
I verified this works in JupyterLab using all of the `setup.py` commands it uses.
cc @gnestor @ellisonbg @SylvainCorlay @jasongrout
=> Add initial distutils file

.travis.yml, jupyter_packaging/__main__.py, jupyter_packaging/setupbase.py, tests/conftest.py, tests/test_is_stale.py, tests/test_main.py, tests/test_which.py
Fixes #9.
Also adds some basic test.
=> Adjust is_stale to use recursive mtimes

jupyter_packaging/setupbase.py
This was created as part of https://github.com/jupyterlab/jupyterlab/pull/3270.  It uses some patterns from the [ipython](https://github.com/ipython/ipython/blob/master/setupbase.py) version.
- adds enhanced support for `npm` and auto-detection of `yarn`.
- adds support for `**` glob patterns in `data_files` and `package_data`.
- adds functions to ensure the python version and get the package version.
- adds a convenience function to create a `Command` that calls a callback when run
- general cleanup
=> Updates from using this as the JupyterLab basis

jupyter_packaging/setupbase.py
Otherwise the `package_data` is not included with `pip install .`.
Also fixes the handling of nested folders in `data_files`.
=> Fix handling of pip install

appveyor.yml
Ensure appveyor actually works :)
=> Add appveyor test dependencies

MANIFEST.in, jupyter_packaging/setupbase.py, setup.cfg, setup.py, tests/test_find_packages.py
Fixes a deprecation warning, and prepares for release.
=> Cleanup pt 2

jupyter_packaging/setupbase.py
To enable this package to be used when imported from an installed package (`import jupyter_packaging`), all paths need to be taken as args or relative to the current directory. Using `HERE` in those cases will simply introspect the installed `jupyter_packaging` install dir.
=> Remove HERE

tests/test_which.py
=> do not pass absolute path to which

.travis.yml, jupyter_packaging/setupbase.py, setup.py, tests/conftest.py, tests/test_develop.py
=> Add handling of data_files in develop mode and add test

README.md
=> Update readme to mention pep 518

jupyter_packaging/setupbase.py, tests/conftest.py, tests/test_datafiles_paths.py, tests/test_install.py
This is currently used in [jupyterlab](https://github.com/jupyterlab/jupyterlab/blob/ca409a5aab9c6362a306698510cba8d939c81796/setup.py#L96).  Part of fixing https://github.com/jupyterlab/jupyterlab/issues/8475
=> Allow files to be excluded

README.md
=> Add local testing instructions

jupyter_packaging/setupbase.py
For some use cases, the "install" command might be sufficient
=> Only run build command if one is given

jupyter_packaging/setupbase.py, tests/conftest.py
Follow up to https://github.com/jupyter/jupyter-packaging/pull/69
Fixes missing local variable and adds a test.
=> Fix Usage of install_npm

README.md, jupyter_packaging/build_api.py, jupyter_packaging/setupbase.py, tests/conftest.py, tests/test_build_api.py, tests/test_install.py
- Fixes handling of backend builder metadata.
- Changes the name from `func` -> `factory` and appropriately uses the factory.
- Adds tests - fixes #74
=> Fixes handling of backend

jupyter_packaging/setupbase.py, tests/test_install.py
=> Do not run ensure_targets in develop mode

jupyter_packaging/setupbase.py, pyproject.toml, setup.cfg, tests/test_utility_functions.py
Fixes jupyter/jupyter-packaging#81
Addresses jupyterlab/jupyterlab#10111
=> Clean up handling of version info

README.md, jupyter_packaging/build_api.py, jupyter_packaging/setupbase.py, tests/conftest.py, tests/test_build_api.py, tests/test_install.py
- Add `skip_if_exists` to `wrap_installers`
- Add support for `skip-if-exists` and `ensured-targets` in `tool.jupyter-packaging.options`
=> Add more options to Build

jupyter_packaging/setupbase.py
Fix boolean logic as a follow-up to #84
=> Fix Handling of Skip If Exists

jupyter_packaging/__init__.py, jupyter_packaging/__main__.py, jupyter_packaging/setupbase.py, setup.py, tests/conftest.py, tests/test_build_api.py
CI should work as before.
Fixes #94.  Fixes #95
=> Some fixes for issues discovered during packaging

README.md
=> Add note about using the build package

tests/test_datafiles_install.py
Package installation should take place within the venv, so use sys.prefix.
=> fix running testsuite within virtualenv

tests/test_datafiles_install.py, tests/test_install.py
=> Enable tests to run in read-only site packages

tests/test_datafiles_install.py, tests/test_deprecated.py, tests/test_install.py, tests/test_utility_functions.py, tests/utils.py
=> Add checks for writable site packages

jupyter_packaging/setupbase.py
cf https://github.com/jupyter/jupyter-packaging/issues/112#issuecomment-980557754
=> Fix docstring to remove deprecation warning

jupyter_packaging/setupbase.py, setup.cfg, tests/utils.py
=> Stop using distutils.log

jupyter_packaging/__main__.py, jupyter_packaging/build_api.py, jupyter_packaging/setupbase.py, tests/conftest.py, tests/test_core_functions.py, tests/test_datafiles_paths.py, tests/test_deprecated.py, tests/utils.py
Fixes #101
`os` is still used especially `os.walk` calls
=> Use pathlib rather than os.path

.github/workflows/check-release.yml, .github/workflows/main.yml, .pre-commit-config.yaml, jupyter_packaging/__init__.py, jupyter_packaging/build_api.py, jupyter_packaging/setupbase.py, pyproject.toml, setup.cfg, tests/conftest.py, tests/test_build_api.py, tests/test_datafiles_install.py, tests/test_deprecated.py, tests/test_install.py, tests/test_utility_functions.py
- Add more checks to `pre-commit`
- Configure `pytest` and fail on unexpected warnings
- Clean up CI and add additional checks
Fixes #136
=> Clean up CI and Tests

jupyter_packaging/setupbase.py
E   DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
=> Replace deprecated pipes.quote with shlex.quote

jupyter_packaging/setupbase.py
=> only remove --skip-npm from argv if it is here

README.md
=> Point users to Hatch Jupyter Builder
