- jupyter_packaging/setupbase.py
Add function `update_package_data`, and call it after each wrapped command.
Resolves #11.
> Update package data after wrapped commands

- jupyter_packaging/setupbase.py
- tests/test_is_stale.py
Previously `recursive_mtimes` assumed path was always a directory. Now it supports files as well.
Also fixes a bug when the target directory was empty.
> Fix `is_stale` for file paths

- jupyter_packaging/setupbase.py
Useful for example when there are local npm dependencies:
```python
cmdclass['jsdeps'] = combine_commands(
install_npm(pjoin(here, 'packageA')),
install_npm(pjoin(here, 'packageB'), force=True),  # Package B depends on A, always install!
)
```
> Add option to force npm install/build

- jupyter_packaging/setupbase.py
- setup.py
- tests/test_find_packages.py
Is there a reason why we roll our own `find_packages` instead of relying on setuptools'?
> Add basic tests + fixes for find_packages

- jupyter_packaging/setupbase.py
- tests/test_ensure_targets.py
- tests/utils.py
Adds a function `ensure_targets` which returns a Command that checks that certain files exist. Useful usage pattern:
```python
combine_commands(
npm_install(node_root),
ensure_targets(expected_build_outputs),
)
```
Similar functionality has been around in many instances of jupyter npm commands as a sort of sanity check, so it should be useful to make it available like this.
> Ensure targets

- jupyter_packaging/setupbase.py
This allows the data_files argument in setup.py to still work.
> Append data files instead of overwrite them

- jupyter_packaging/setupbase.py
The previous usage was wrong (my bad).  This separates it out into a convenience function.  Example:
```python
data_files = expand_data_files([
('share/jupyter/nbextensions/{{ cookiecutter.npm_package_name }}', pjoin(static, '*.js*')),
('share/jupyter/lab/extensions', tar_path)
])
```
cf https://github.com/vidartf/opinionated-widget-cookiecutter/pull/1
> Fix handling of data files

- jupyter_packaging/setupbase.py
allowing install without setuptools results in missing entrypoints and inconsistent installs, which should be avoided.
restores bdist_egg_disabled to prevent `setup.py install` laying implicit eggs.
Also add missing user_options on CombinedCommand, preventing combined commands from running.
> restore setuptools import

- tests/test_find_packages.py
This test was failing when I ran it.
The test checks whether or not packages are found with `find_packages`, but the test was written such that the order the files are read from the file system matters. Both Python 2.7 and 3.x make no guarantees about the order the files are read.
Using a `set` addresses this.
> Fixed a broken test in test_find_packages

- appveyor.yml
- jupyter_packaging/setupbase.py
- tests/test_datafiles_paths.py
- Adds a some tests for `_get_data_files()`, some of which fail.
- Fixes related issues.
- Adds appveyor config. After enabling appveyor for this repo, this should ensure that the tests are also run on Windows platform, which is needed to avoid pathing regressions when using backslash as pathing separator.
> Data spec path issues

- jupyter_packaging/setupbase.py
The BeakerX project ships gradle with the repo and this is not found in the user's path by default, so the call to `which()` returns `None` which is then passed as the first argument to `subprocess.check_call`.
```
>>> from setupbase import run
>>> run("foo")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jmsdnns/Projects/twosigma/bx/jupyter-packaging/jupyter_packaging/setupbase.py", line 219, in run
return subprocess.check_call(cmd, **kwargs)
File "/usr/lib/python3.6/subprocess.py", line 286, in check_call
retcode = call(*popenargs, **kwargs)
File "/usr/lib/python3.6/subprocess.py", line 267, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
restore_signals, start_new_session)
File …
```
> Additional error checking in run()

- tests/test_which.py
This test fails on systems where Python 2 is missing. Let us look for the actual python executable.
> which finds python executable

- .travis.yml
- appveyor.yml
- jupyter_packaging/setupbase.py
- setup.py
- tests/conftest.py
Fixes #43.  Fixes  #24
- Tests using pyproject.toml
- Deprecates `ensure_python` in favor of the builtin `python_requires`
- Sets minimum version to Python 3.6.
> Test using pyproject.toml and modernize

- jupyter_packaging/setupbase.py
This fixes some issues we are seeing that stem from differences between distutils and setuptools.
> Import sdist from distutils instead of setuptools

- jupyter_packaging/setupbase.py
This PR makes a change from `sys.prefix` to `self.install_base` to allow top-level command to set the --prefix or --install_dir.
> Allow --prefix to work

- jupyter_packaging/setupbase.py
Upstreaming from https://github.com/bqplot/bqplot/pull/1235 to make source package skip the npm build step. Note, I cannot test this, because I don't know how. Since running pip install will fetch jupyter_packaging from pypi, how can I use my local dev install? cc @martinRenou
> feat: add skip_if_exists command to skip when paths exists

- jupyter_packaging/setupbase.py
- tests/test_datafiles_paths.py
I had a "tatic" folder in my install, so I figured something was wrong. I remembered trailing slashes being a sensitive topic, and removing that fixed it, but I'd also like to prevent myself from making the same mistake in the future 😄 
I couldn't see any reason why a trailing slash would ever be desired, and no unit tests complained, so assuming this will be strictly better.
> allow trailing slashes in spec

- tests/test_datafiles_paths.py
If I understood https://github.com/jupyter/jupyter-packaging/issues/50 correctly, this test should cover the case mentioned in the description. I do not know if the issue was fixed elsewhere, or if the test is "wrong", but it seems to pass as it is?
> test for nested source folder

- jupyter_packaging/setupbase.py
Follow-up to https://github.com/jupyter/jupyter-packaging/pull/54 based on the discussion in https://github.com/jupyter/jupyter-packaging/pull/54#discussion_r545753631
The command should not be skipped if any of the files is missing.
> Fix skip_if_exists logic

- jupyter_packaging/setupbase.py
Turns out there was a typo in the `should_skip` function revealed by https://github.com/jupyter/jupyter-packaging/pull/58
> Fix typo in skip_if_exists

- tests/conftest.py
- tests/test_skip_if_exists.py
Simple test to at least cover the code path.
> Add basic test for skip_if_exists

- jupyter_packaging/setupbase.py
Package data spec does not work with leading "./"
> Fix packagedata docstring examples

- jupyter_packaging/setupbase.py
Currently, if using jupyter-packaging in a package with ``pyproject.toml`` and building an sdist with ``python -m build --sdist``, many package files, including ``setup.py`` as well as files defined in ``MANIFEST.in`` don't get included in the source distribution. This is solved by wrapping setuptools' rather than distutils' ``sdist`` command.
> Use sdist from setuptools not distutils

- jupyter_packaging/setupbase.py
Hi everyone! 
I had a problem here when I tried to install my package locally (using jupyter-package):
```sh 
$ python setup.py develop
running develop
running builder
error: invalid command 'builder'
``` 
To fix that (locally) I used:
```python 
try:
from jupyter_packaging import wrap_installers, npm_builder
builder = npm_builder(build_cmd="build:prod")
builder.__name__ = "pre_develop"
cmdclass = wrap_installers(pre_develop=builder)
except ImportError:
cmdclass = {}
if __name__ == '__main__':
setuptools.setup(cmdclass=cmdclass)
```
Not sure if it is something wrong just for me. This PR fixes this problem, forcing the correct name of the function.
> Fix invalid command build

- jupyter_packaging/setupbase.py
- setup.cfg
- tests/test_utility_functions.py
Adds a `get_version_info` helper function to get the `version_info` tuple commonly used in Jupyter packages given a version string.
> Add version info helper function

- jupyter_packaging/setupbase.py
- tests/conftest.py
- tests/test_install.py
Adds `ensured_targets` option to `wrap_installers` to ensure generated assets are available before running the dist commands.
> Add ability to ensure targets

- README.md
- jupyter_packaging/setupbase.py
- tests/test_deprecated.py
- tests/test_utility_functions.py
- Recommend against using `jupyter_packaging` as a runtime dependency
- Deprecate `get_version_info` in favor of an inline parser with no dependencies
> Deprecate `get_version_info` and recommend against runtime dependency

- jupyter_packaging/setupbase.py
The docstring for `npm_builder` said that `npm` could be a string, but it was treated as a list.
> Fix Handling of npm Parameter

- tests/conftest.py
Fix usage of setuptools metadata in tests to address recent failures seen in [CI](https://github.com/jupyter/jupyter-packaging/actions/runs/953416978). The new version of [build](https://github.com/pypa/build/releases/tag/0.5.0) package is less permissive than the previous in handling module metadata.
> Fix handling of module metadata in tests

- jupyter_packaging/setupbase.py
- tests/test_deprecated.py
Fixes: https://github.com/jupyter/jupyter-packaging/issues/93
> Disallow deprecated function return incorrect results for Python 3.10

- jupyter_packaging/setupbase.py
- tests/test_core_functions.py
Fix handling of `yarn.lock` file when `yarn` is not available.
> Handle missing yarn

- jupyter_packaging/setupbase.py
- tests/test_utility_functions.py
I'm sorry, it seems that I missed this one. I've prepared this PR in a browser so please test it before merging.
> Fix last one hardcoded unversioned python command

- jupyter_packaging/setupbase.py
This PR is forwarded from ipython/ipyparallel#586.
The import of bdist_wheel is optional:
https://github.com/jupyter/jupyter-packaging/blob/b0304d0c07e06f6f7933300e6c841ac006b89e91/jupyter_packaging/setupbase.py#L46-L49
Just like the use of it is None protected here:
https://github.com/jupyter/jupyter-packaging/blob/b0304d0c07e06f6f7933300e6c841ac006b89e91/jupyter_packaging/setupbase.py#L579-L580
The use here must be None protected too:
https://github.com/jupyter/jupyter-packaging/blob/b0304d0c07e06f6f7933300e6c841ac006b89e91/jupyter_packaging/setupbase.py#L145
> The import of bdist_wheel is optional, must check for None before using it

- README.md
> README: clarify build system version

- setup.cfg
Explicitly exclude tests from being found by find_packages().
Otherwise, they are installed as top-level site-packages/tests.
> do not install tests as a top-level package

- jupyter_packaging/setupbase.py
with pip, passing command-line arguments to setup doesn't always work. Environment variables are more reliable.
> Allow skipping npm with JUPYTER_PACKAGING_SKIP_NPM env

- CHANGELOG.md
Automated Changelog Entry for 0.12.2 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter/jupyter-packaging  |
| Branch  | main  |
| Version Spec | next |
| Since | v0.12.1 |
> Automated Changelog Entry for 0.12.2 on main

- CHANGELOG.md
Automated Changelog Entry for 0.12.3 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | jupyter/jupyter-packaging  |
| Branch  | main  |
| Version Spec | next |
| Since | v0.12.2 |
> Automated Changelog Entry for 0.12.3 on main

- .github/workflows/main.yml
The package was deleted from PyPI.  We're still enforcing coverage in the build.
> Remove codecov usage
